### PR TITLE
Rails-Blog:  API-Endpoint

### PR DESCRIPTION
**Pull request by ZikaZaki**
# Rails-Blog:  API-Endpoint
## In this pull-request we did the followings:
- [x] Created an API endpoint to list all posts for a user.
- [x] Created an API endpoint to list all comments for a user's post.
- [x] Created an API endpoint to add a comment to a post. Remember that the owner of the comment is the user that makes it; it should **not** be set by passing a parameter.
- [x] Added authentication to your API endpoints.
- [x] Your API endpoints should receive JSON and respond JSON as well.
- [x] Made sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- [x] Made sure that I used correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- [x] Made sure that I documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
- [x] Made sure to follow the list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not contributed by all 3 assigned pair group members. Kindly ensure that **all** assigned pair members contribute evenly to this project, and then kindly request another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ZikaZaki** [comment]
Thanks @rloterh for your time. My coding partner has already contributed to the project.

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Team,  

Your project is complete! 🏁 Great job! There is nothing else to say other than... it's time to merge it 🍾🍾🍾 Congratulations!  🎉💯🌟 

## Highlights 🎯 
- API endpoints properly implemented!
- Good ReadMe

## Optional suggestions 🧰 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

**You can also consider:**
- Kindly include details of the other co-contributor(s) in your ReadMe.
- Kindly endeavor to fill the FAQ section with at least 2 Q&A(s), or optionally remove this section.
- MIT license link in your ReadMe is broken, kindly endeavor to fix it, and remove the guide note below it.
Implementing the above change(s) will make your ReadMe/ repository stand out even better! 👌

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ZikaZaki** [comment]
Thanks @rloterh, we will update the README.md.

**Pull request merged**
